.github/dependabot.yml, .github/pull_request_template.md, cardea-data/src/main/java/ShesmuCaseStatus.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/ShesmuCase.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/controller/CardeaApiController.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/service/CaseService.java, cardea-server/src/main/resources/application.yml, changes/add_shesmu-cases_endpoint.md, release.sh
=> Add shesmu-cases endpoint

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/ShesmuCase.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/controller/StatusController.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/service/CaseService.java, changes/fix_forward_headers.md, example-application.properties
=> Forward headers to ensure correct URL in OpenAPI docs

cardea-data/pom.xml, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Assay.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Case.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/CaseData.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/CaseStatusCountsForRun.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Donor.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Lane.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Metric.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/MetricSubcategory.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/OmittedSample.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Project.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Requisition.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/RequisitionQc.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/RequisitionQcGroup.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Run.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/RunAndLibraries.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Sample.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Test.java
=> Replace Immutable annotation with javadocs

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Sample.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/CaseLoader.java, changes/add_medianInsert.md
Jira ticket: https://jira.oicr.on.ca/browse/GLT-3957
=> [GLT-3957] added sample median insert size

cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/service/CaseService.java, changes/fix_only_iuses_for_shesmu-cases.md
=> Only use IUS lims IDs for shesmu-cases endpoint

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Case.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Test.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/CaseLoader.java, changes/add_GP-4028.md
Jira ticket: https://jira.oicr.on.ca/browse/GP-4028
- ✅ Includes a change file
- ✅ Updates developer documentation
=> [GP-4028] Updated Test and Case data models to match Dimsum

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Sample.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/CaseLoader.java, changes/add_qcNotes.md
Jira ticket: https://jira.oicr.on.ca/browse/GLT-3975
=> [GLT-3975] added sample QC notes

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Assay.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Case.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Donor.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Lane.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Metric.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/MetricSubcategory.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/OmittedSample.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Project.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Requisition.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/RequisitionQc.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/RequisitionQcGroup.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Run.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/RunAndLibraries.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Sample.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Test.java, changes/add_GLT-3978.md
Jira ticket: https://jira.oicr.on.ca/browse/GLT-3978
✅Includes a change file
✅ Updates developer documentation
=> [GLT-3978] Allowing Jackson to parse JSON data into these models using Builder notation

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Case.java, changes/change_GLT-3938.md
Jira ticket: https://jira.oicr.on.ca/browse/GLT-3938
- ✅ Includes a change file
- ✅ Updates developer documentation
=> [GLT-3938] change Case data type to match Dimsum

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Case.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/CaseData.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Sample.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/CaseLoader.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/service/CaseService.java, cardea-server/src/test/java/ca/on/oicr/gsi/cardea/server/CaseLoaderTest.java, cardea-server/src/test/java/ca/on/oicr/gsi/cardea/server/MockCase.java, changes/change_GLT-3938.md, changes/change_GLT-3988.md
Jira ticket: https://jira.oicr.on.ca/browse/GLT-3988
- ✅ Includes a change file
- ✅ Updates developer documentation
=> [GLT-3988] update data types

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Case.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/CaseLoader.java, cardea-server/src/test/resources/testdata/cases.json, changes/change_startDate.md
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4022
QC-Gate-ETL release will need to happen before this since start date is required (non-null) here
=> [GLT-4022] use case start date provided by QC-Gate-ETL

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Case.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Requisition.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Test.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/CaseLoader.java, cardea-server/src/test/resources/testdata/cases.json, cardea-server/src/test/resources/testdata/requisitions.json, changes/add_pauses.md, changes/add_tat.md
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4035
=> [GLT-4035] added TAT and pause data

cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/CaseLoader.java, changes/fix_supplemental_noreq.md
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4071
=> [GLT-4071] fixed loading samples with no requisition

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Deliverable.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/CaseLoader.java, cardea-server/src/test/resources/testdata/cases.json, changes/add_deliverable_qcNotes.md
Jira ticket: https://jira.oicr.on.ca/browse/GLT-3964
=> [GLT-3964] added QC notes to deliverables

cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/service/CaseService.java, changes/fix_shesmu_completedDate.md
Jira ticket: https://jira.oicr.on.ca/browse/GP-4207
=> [GLT-4207] fixed missing shesmu-cases completedDates

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/CaseDeliverable.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/CaseDeliverableImpl.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/CaseLoader.java, cardea-server/src/test/resources/testdata/cases.json, changes/add_deliverableTat.md
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4096
=> [GLT-4096] added deliverable-type level TAT fields

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Project.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/CaseLoader.java, cardea-server/src/test/resources/testdata/projects.json, changes/add_analysisReviewSkipped.md
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4120
=> [GLT-4120] added project analysisReviewSkipped field

cardea-data/pom.xml, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Assay.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Case.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/CaseDeliverableImpl.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/CaseImpl.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/CaseStatus.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Sample.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/ShesmuCase.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/Test.java, cardea-data/src/test/java/ca/on/oicr/gsi/cardea/JacksonTest.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/service/CaseService.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4129
Target branch is the multi-assay req PR to cover changes made in that branch too
=> [GLT-4129] added tests for Jackson serial/deserialization

README.md
=> simplify mvn run command and clarify instructions

README.md, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/service/CaseService.java, changes/fix_qcfailed_field.md
=> fix qcFailed to handle null correctly

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/CaseDeliverable.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/CaseDeliverableImpl.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/CaseQc.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/CaseRelease.java, cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/CaseReleaseImpl.java, cardea-data/src/test/java/ca/on/oicr/gsi/cardea/JacksonTest.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/CaseLoader.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/service/CaseService.java, cardea-server/src/test/java/ca/on/oicr/gsi/cardea/server/CaseLoaderTest.java, cardea-server/src/test/java/ca/on/oicr/gsi/cardea/server/MockCase.java, cardea-server/src/test/java/ca/on/oicr/gsi/cardea/server/service/CaseServiceTest.java, cardea-server/src/test/resources/testdata/cases.json, changes/change_release_qcs.md
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4289
=> [GLT-4289] added new release QC statuses

cardea-data/pom.xml, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/SecurityConfigurationNoAuth.java, pom.xml
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4326
=> [GLT-4326] updated to Spring Boot 3.4

cardea-data/src/main/java/ca/on/oicr/gsi/cardea/data/ShesmuDetailedCase.java, changes/fix_clinicalCompletedDate.md
Jira ticket: https://jira.oicr.on.ca/browse/GP-4534
=> fix clinicalCompletedDate

.github/pull_request_template.md
=> Update PR template with process for updating benchmarking script in case shesmu data models change

cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/service/CaseService.java, changes/fix_sample_complete_logic.md
Jira ticket:
- infrastructure PR should have a title like "Merge during Cardea release: [rest of the title]" and BL will merge during release
=> fix sample complete logic

cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/service/CaseService.java, changes/change_shesmu-detailed-cases.md
Jira ticket:
https://jira.oicr.on.ca/browse/GP-4622
https://jira.oicr.on.ca/browse/GP-4603
- infrastructure PR should have a title like "Merge during Cardea release: [rest of the title]" and BL will merge during release
=> shesmu-detailed-cases include all cases and sort

cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/CaseUtils.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/controller/CardeaApiController.java, cardea-server/src/main/java/ca/on/oicr/gsi/cardea/server/service/CaseService.java, cardea-server/src/test/java/ca/on/oicr/gsi/cardea/server/CaseUtilsTest.java, changes/add_casePriority.md
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4400
- infrastructure PR should have a title like "Merge during Cardea release: [rest of the title]" and BL will merge during release
=> [GLT-4400] added case priority endpoint
